FROM nginx

LABEL AUTHOR="Ivan Ermilov <ivan.s.ermilov@gmail.com>"
LABEL MAINTAINER="Francisco C J Bispo <fcjbispo@franciscobispo.net>"

COPY default.conf /etc/nginx/conf.d/default.conf
COPY materialize.min.css /data/bde-css/materialize.min.css
COPY bde-hadoop.css /data/bde-css/bde-hadoop.css
